---
- name: Install Docker base packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    update_cache: true
    name: docker-ce
    state: present

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Create plugins  directory for user
  become: false
  ansible.builtin.file:
    state: directory
    path: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins"
    mode: "0755"

- name: Download Docker Compose
  become: false
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64
    dest: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins/docker-compose"
    mode: "0755"

# - name: Make Docker Compose executable
#  become: false
#  ansible.builtin.file:
#    path: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins/docker-compose"
#    mode: "0755"
